config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get '/upcoming', to: 'welcome#events'
  resources :users do
    resources :events
  end
  resources :user_sessions, only: [:create, :destroy]
  delete '/sign_out', to: 'user_sessions#destroy', as: :sign_out
  get '/sign_in', to: 'user_sessions#new', as: :sign_in
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :user

    validates :title, presence: true
    validates :visible, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :events, dependent: :destroy
    acts_as_authentic do |c|
        c.crypto_provider = Authlogic::CryptoProviders::BCrypt
    end

    # Validate email, login, and password as you see fit.
    #
    validates :email,
      format: {
        with: /@/,
        message: "should look like an email address."
      },
      length: { maximum: 100 },
      uniqueness: {
        case_sensitive: false,
        if: :will_save_change_to_email?
      }
  
    validates :password,
      confirmation: { if: :require_password? },
      length: {
        minimum: 8,
        if: :require_password?
      }
    validates :password_confirmation,
      length: {
        minimum: 8,
        if: :require_password?
    }

    validates :name, presence: true
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper :all
    helper_method :current_user_session, :current_user

    private
      def current_user_session
        return @current_user_session if defined?(@current_user_session)
        @current_user_session = UserSession.find
      end
  
      def current_user
        return @current_user if defined?(@current_user)
        @current_user = current_user_session && current_user_session.user
      end

      def require_user
        unless current_user
          store_location
          flash[:notice] = "You must be logged in to access this page"
          redirect_to sign_in_url
          return false
        end
      end

      def require_no_user
        if current_user
          store_location
          flash[:notice] = "You must be logged out to access this page"
          redirect_to user_path(current_user)
          return false
        end
      end

      def store_location
        session[:return_to] = request.original_url
      end

    protected

    def handle_unverified_request
        # raise an exception
        fail ActionController::InvalidAuthenticityToken
        # or destroy session, redirect
        if current_user_session
            current_user_session.destroy
        end
        redirect_to root_url
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    before_action :require_user

    def index
        @user = current_user
        @events = @user.events.all
    end

    def create
        @user = @current_user
        @event = @user.events.new(event_params)

        if @event.save
            flash[:notice] = "Event created successfully!"
            redirect_to @user
        else
            render :new
        end
    end

    def new
        @user = @current_user
        @event = @user.events.new
    end

    def edit
        @user = @current_user
        @event = @user.events.find(params[:id])
    end

    def show
        @user = @current_user
        @event = @user.events.find(params[:id])
    end

    def update
        @user = @current_user
        @event = @user.events.find(params[:id])

        if @event.update(event_params)
            flash[:notice] = "Event updated successfully!"
            redirect_to user_event_path(@user,@event)
        else
            render :edit
        end
    end

    def destroy
        @user = @current_user
        @event = @user.events.find(params[:id])
        @event.destroy
        flash[:notice] = "Event deleted successfully!"

        redirect_to user_path(@user)
    end

    private
    def event_params
        params.require(:event).permit(:title,:description, :pay_status,
        :from, :to, :event_status, :visible, :location)
    end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
    before_action :require_no_user, :only => [:new, :create]
    before_action :require_user, :only => :destroy
    def new
        @user_session = UserSession.new
      end
    
    def create
        @user_session = UserSession.new(user_session_params.to_h)
        if @user_session.save
            flash[:notice] = "Login successful!"
            redirect_to user_path(@user_session.user)
        else
            render :action => :new
        end
    end
    
    def destroy
        current_user_session.destroy
        flash[:notice] = "Logout successful!"
        redirect_to root_path
    end

    private

    def user_session_params
        params.require(:user_session).permit(:email, :password, :remember_me)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_no_user, :only => [:new, :create]
    before_action :require_user, :only => [:edit, :show, :update, :destroy]

    def create
        @user = User.new(user_params)

        if @user.save
            flash[:success] = "Account registered!"
            redirect_to @user
        else
            render :new
        end
    end

    def new
        @user = User.new
    end

    def edit
        @user = @current_user
    end

    def show
        @user = @current_user
    end

    def update
        @user = @current_user

        if @user.update(user_params)
            flash[:notice] = "Update successful!"
            redirect_to @user
        else
            render :edit
        end
    end

    def destroy
        @user = @current_user
        @user.destroy

        redirect_to root_path
    end

    private
    def user_params
        params.require(:user).permit(:name,:email, :phone, :password, :password_confirmation)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def events
    @events = Event.where(visible: 'everybody', event_status: 'ready').order(created_at: :desc)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/_event.html.erb
<h3><%= link_to event.title, user_event_path(@user,event) %></h3>
<p><%= event.description %></p>

app/views/events/_form.html.erb
<%= form_with model: [ current_user, @event] do |form| %>
    <div>
      <%= form.label :title %><br>
      <%= form.text_field :title %>
      <% event.errors.full_messages_for(:title).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  
    <div>
      <%= form.label :description %><br>
      <%= form.text_area :description, size: "70x5" %><br>
      <% event.errors.full_messages_for(:description).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div>
        <%= form.label :location %><br>
        <%= form.text_area :location %><br>
        <% event.errors.full_messages_for(:location).each do |message| %>
          <div><%= message %></div>
        <% end %>
    </div>
        
    <div>
      <%= form.label :pay_status, "Is the Event free or paid?" %><br>
      <%= form.select :pay_status, ['free', 'paid'], selected: 'free' %>
    </div>

    <div>
      <%= form.label :from, "Start Date and Time" %><br>
      <%= form.datetime_local_field :from %><br>
      <% event.errors.full_messages_for(:from).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div>
      <%= form.label :to, "End Date and Time" %><br>
      <%= form.datetime_local_field :to %><br>
      <% event.errors.full_messages_for(:to).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div>
        <%= form.label :visible, "Would you like this event to show up on the main page?" %>
        <%= form.select :visible, ['everybody','private'], selected: 'private' %>
    </div>

    <div>
      <%= form.label :event_status, "Event Status" %><br>
      <%= form.select :event_status, ['ready','pending'], selected: 'pending' %>
    </div>

    <div>
      <%= form.submit %>
    </div>
  <% end %>
  

app/views/events/edit.html.erb
<h1> Edit Event </h1>

<%= render "form", user: current_user, event: @event %>

app/views/events/index.html.erb
<h1>Events</h1>

<ul>
  <% @events.each do |event| %>
    <li>
        <%= link_to event.title, user_event_path(current_user, event.id) %>
    </li>
  <% end %>
</ul>

<%= link_to "New Event", new_user_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render "form", user: current_user, event: @event %>

app/views/events/show.html.erb
<h1><%= @event.title %></h1>

<h2>Description</h2>
<p><%= @event.description %></p>

<h2>Location</h2>
<p><%= @event.location %></p>

<h2>Date and Time</h2>
<p>From <%= @event.from %> === to === <%= @event.to %></p>

<h2>Status</h2>
<p><%= @event.event_status %> <%= @event.pay_status %> Event</p>

<h2>Visibility</h2>
<p><%= @event.visible %></p>

<ul>
  <li><%= link_to "Edit", edit_user_event_path(current_user,@event) %></li>
  <li><%= link_to "Destroy", user_event_path(current_user,@event),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %></li>
  <li><%= link_to "Profile", user_path(current_user) %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tixtest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <%= link_to 'Tixtest', root_path, class: 'navbar-brand' %>
    </div>
    <div id="navbar">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Home', root_path %></li>
      </ul>
      <ul class="nav navbar-nav pull-right">
        <% if current_user %>
          <li><span><%= current_user.email %></span></li>
          <li><span><%= link_to "Profile", user_path(current_user) %></span></li>
          <li><%= link_to 'Sign Out', sign_out_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Sign In', sign_in_path %></li>
          <li><%= link_to 'Sign Up', new_user_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
  </nav>
  <div class="container">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
      <%= value %>
    </div>
  <% end %>
    <%= yield %>
  </body>
</html>

app/views/user_sessions/new.html.erb
<%= form_for @user_session, url: user_sessions_path do |f| %>
    <% if @user_session.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_session.errors.count, "error") %> prohibited:</h2>
      <ul>
        <% @user_session.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
    <%= f.label :email %><br />
    <%= f.text_field :email %><br />
    <br />
    <%= f.label :password %><br />
    <%= f.password_field :password %><br />
    <br />
    <%= f.label :remember_me %><br />
    <%= f.check_box :remember_me %><br />
    <br />
    <%= f.submit "Login" %>
  <% end %>

app/views/users/_form.html.erb
<%= form_with model: user do |form| %>
    <div class="form-group">
      <%= form.label :name,"Username" %><br>
      <%= form.text_field :name, class: 'form-control' %>
      <% user.errors.full_messages_for(:name).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  
    <div class="form-group">
      <%= form.label :email %><br>
      <%= form.email_field :email, class: 'form-control' %><br>
      <% user.errors.full_messages_for(:email).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
        
    <div class="form-group">
      <%= form.label :phone %><br>
      <%= form.telephone_field :phone, class: 'form-control' %>
    </div>

    <div class="form-group">
    <%= form.label :password %>
    <%= form.password_field :password, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, class: 'form-control' %>
  </div>

    <div>
      <%= form.submit class: 'btn btn-primary btn-lg' %>
    </div>
  <% end %>
  

app/views/users/edit.html.erb
<h1> Edit User </h1>

<%= render "form", user: current_user %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render "form", user: @user %>

app/views/users/show.html.erb
<h1>Welcome <%= current_user.name %></h1>

<h2>Events</h2>
<p><%= render current_user.events %></p>

<ul>
  <li><%= link_to "New Event", new_user_event_path(current_user)%></li>
  <li><%= link_to "Manage Events", user_events_path(current_user)%></li>
  <li><%= link_to "Edit account settings", edit_user_path(current_user) %></li>
  <li><%= link_to "Delete account", user_path(current_user),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %></li>
</ul>

app/views/welcome/events.html.erb
<h1>Events</h1>

<ul>
  <% @events.each do |event| %>
    <li>
        <%= event.title%> created by <%= event.user.name %>
    </li>
  <% end %>
</ul>

app/views/welcome/index.html.erb
<h1>Welcome</h1>
<div class="container"><p>This is an events management application</p></div>
<p class="nav navbar-nav pull-right"><%= link_to "Upcoming events", upcoming_path %></p>